server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Vue SPA를 위한 설정 (리프레시 시 404 방지)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
