services:
  db:
    image: postgres:16
    container_name: jeeuni-postgres
    restart: always
    env_file:
      - ./.env
    networks:
      - backend_net
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jeeuni-backend
    restart: always
    env_file:
      - ./backend/.env.local
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - frontend_net
      - backend_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://127.0.0.1:8000
    container_name: jeeuni-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - frontend_net

# -------------------------
# NETWORK DEFINITIONS
# -------------------------
networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

# -------------------------
# VOLUME DEFINITIONS
# -------------------------
volumes:
  postgres_data:
