# Generated by Django 5.2.1 on 2025-05-23 13:16

import literacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteracyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='질문 텍스트', max_length=300)),
                ('content', models.TextField(blank=True, help_text='문제 지문 텍스트', null=True)),
                ('img_content', models.ImageField(blank=True, help_text='문제 지문 이미지', null=True, upload_to='literacy_tests/')),
                ('choices', models.JSONField(help_text="보기 배열, ex. ['30,050','30,500','300,050','300,500']")),
                ('answer', models.PositiveSmallIntegerField(help_text='정답 번호 (1~4)')),
                ('level', models.PositiveSmallIntegerField(help_text='난이도 레벨 (1~5)')),
            ],
            options={
                'db_table': 'literacy_test',
                'ordering': ['level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LiteracyCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literacy_level', models.PositiveSmallIntegerField(help_text='문해력 수준 (1~5)', unique=True)),
                ('level_criteria', models.JSONField(help_text='정규 판단 기준(JSON)', validators=[literacy.models.validate_level_criteria])),
                ('exception_allowed', models.JSONField(blank=True, help_text='예외 허용 조건(JSON, 선택)', null=True, validators=[literacy.models.validate_exception_allowed])),
                ('feedback', models.TextField(help_text='해당 수준 피드백')),
                ('recommendation', models.TextField(help_text='해당 수준 추천 학습 활동')),
            ],
            options={
                'db_table': 'literacy_criteria',
                'ordering': ['literacy_level'],
                'indexes': [models.Index(fields=['literacy_level'], name='idx_literacy_level')],
            },
        ),
    ]
